# Generated by Django 6.1.1 on 2026-09-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Reunión', 'Reunión'), ('Atención', 'Atención'), ('Terreno', 'Terreno'), ('Seguimiento', 'Seguimiento')], max_length=30)),
                ('estado', models.CharField(choices=[('Validada', 'Validada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20)),
                ('evidencia', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='app_funcionarios.funcionario')),
            ],
        ),
    ]
